/* The hero artwork. Renders the on-chain tokenURI SVG when available; falls
   back to the v3 placeholder when the renderer read fails or is null. */
import {getTokenTicker} from '@/lib/config';

export function Artwork({svgMarkup}: {svgMarkup?: string | null}) {
    return (
        <div className="artwork-wrap">
            <div className="artwork" role="img" aria-label="Permanent Collection live state — 111-trait grid">
                {svgMarkup ? (
                    <div
                        className="artwork-svg"
                        // The SVG is generated by our own on-chain renderer; safe to inline.
                        dangerouslySetInnerHTML={{__html: svgMarkup}}
                    />
                ) : (
                    <>
                        <div className="artwork-grid" aria-hidden="true" />
                        <span className="artwork-watermark">{getTokenTicker()} tokenURI artwork</span>
                    </>
                )}
            </div>
            <style>{styles}</style>
        </div>
    );
}

const styles = `
.artwork-wrap {
    display: flex;
    flex-direction: column;
    gap: 14px;
}
.artwork {
    aspect-ratio: 1;
    background: #1c1c1c;
    border: 1px solid var(--line);
    position: relative;
    overflow: hidden;
    box-shadow: 0 18px 60px rgba(0, 0, 0, 0.14);
}
.artwork-grid {
    position: absolute;
    inset: 9%;
    background: linear-gradient(
            90deg,
            rgba(255, 255, 255, 0.08) 1px,
            transparent 1px
        ),
        linear-gradient(rgba(255, 255, 255, 0.08) 1px, transparent 1px);
    background-size: 9.09% 9.09%;
}
.artwork-watermark {
    position: absolute;
    left: 28px;
    bottom: 26px;
    font-family: var(--mono);
    font-size: 12px;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: rgba(255, 255, 255, 0.8);
    opacity: 0.8;
}
.artwork-svg {
    position: absolute;
    inset: 0;
    display: flex;
    align-items: center;
    justify-content: center;
}
.artwork-svg svg {
    width: 100%;
    height: 100%;
    display: block;
}
`;
