import {NextResponse} from 'next/server';
import {createPublicClient, http, fallback, parseAbi} from 'viem';
import {mainnet} from 'viem/chains';
import {getDataAdapter} from '@/lib/data';
import {renderPunkTileContent} from '@/lib/trait-tile';
import {getContractAddresses, getRpcUrls} from '@/lib/config';
import {abi as CryptoPunksMarketAbi} from '@/lib/abis/CryptoPunksMarket';
import type {Address} from '@/lib/data/types';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/** The autogenerated CryptoPunksMarket ABI doesn't include the bids view —
 *  inline it here. Return tuple matches the 2017 contract:
 *  (hasBid, punkIndex, bidder, value). */
const PUNK_BIDS_ABI = parseAbi([
    'function punkBids(uint256) view returns (bool, uint256, address, uint256)',
]);

function getRpc() {
    const urls = getRpcUrls();
    const transports = urls.map((u) => http(u));
    return createPublicClient({
        chain: mainnet,
        transport: transports.length > 1 ? fallback(transports) : transports[0],
    });
}

const ZERO = '0x0000000000000000000000000000000000000000';

interface BidInfo {
    /** Wei amount of the highest standing bid on the 2017 market, or '0'
     *  if no active bid (or bidder == zero). Stringified for JSON transport. */
    valueWei: string;
    bidder: string;
}

interface ListingInfo {
    /** Public listing price in wei, stringified. Only set for listings the
     *  caller can actually buy: `onlySellTo == zero && minValue > 0`. */
    minValueWei: string;
}

/**
 * GET /api/owned-punks?address=0x...
 *
 * Returns the Punk ids currently held by `address`, plus per-Punk visuals
 * (pre-rendered SVG inner content) and market context (highest standing
 * 2017-market bid + public listing if any). The market data lets the owner
 * compare Patron's offer against what the open market is paying — context
 * that prevents the "I sold for less than I could have got" surprise.
 */
export async function GET(req: Request) {
    const u = new URL(req.url);
    const raw = u.searchParams.get('address');
    if (!raw || !/^0x[0-9a-fA-F]{40}$/.test(raw)) {
        return NextResponse.json(
            {error: 'address must be a 0x-prefixed 20-byte address'},
            {status: 400},
        );
    }
    const address = raw as Address;

    try {
        const punkIds = await getDataAdapter().getPunksOwnedBy(address);
        const svgsByPunkId: Record<number, string> = {};
        for (const id of punkIds) {
            svgsByPunkId[id] = renderPunkTileContent(id);
        }
        // Per-punk market context. Two multicalls (one per view) keep batch
        // sizes small; for the realistic case of a wallet holding handfuls
        // of Punks the round trips are negligible.
        const bidsByPunkId: Record<number, BidInfo> = {};
        const listingsByPunkId: Record<number, ListingInfo> = {};
        if (punkIds.length > 0) {
            const addrs = getContractAddresses();
            const rpc = getRpc();
            const bidCalls = punkIds.map((id) => ({
                address: addrs.punksMarket,
                abi: PUNK_BIDS_ABI,
                functionName: 'punkBids' as const,
                args: [BigInt(id)] as const,
            }));
            const listingCalls = punkIds.map((id) => ({
                address: addrs.punksMarket,
                abi: CryptoPunksMarketAbi,
                functionName: 'punksOfferedForSale' as const,
                args: [BigInt(id)] as const,
            }));
            const [bidsResults, listingResults] = await Promise.all([
                rpc.multicall({contracts: bidCalls, allowFailure: true}),
                rpc.multicall({contracts: listingCalls, allowFailure: true}),
            ]);
            for (let i = 0; i < punkIds.length; i++) {
                const id = punkIds[i];
                const bidRes = bidsResults[i];
                if (bidRes.status === 'success') {
                    const [hasBid, , bidder, value] = bidRes.result as readonly [
                        boolean,
                        bigint,
                        Address,
                        bigint,
                    ];
                    if (hasBid && bidder !== ZERO && value > 0n) {
                        bidsByPunkId[id] = {valueWei: value.toString(), bidder};
                    }
                }
                const listRes = listingResults[i];
                if (listRes.status === 'success') {
                    const [isForSale, , , minValue, onlySellTo] = listRes.result as readonly [
                        boolean,
                        bigint,
                        Address,
                        bigint,
                        Address,
                    ];
                    // Only surface listings the open market can actually
                    // hit. `onlySellTo == zero && minValue > 0` is a true
                    // public listing; the `acceptBid` pre-listing
                    // (priced at or below the live bid, onlySellTo == Patron)
                    // and other direct-only listings are noise here.
                    if (isForSale && onlySellTo === ZERO && minValue > 0n) {
                        listingsByPunkId[id] = {minValueWei: minValue.toString()};
                    }
                }
            }
        }
        return NextResponse.json({punkIds, svgsByPunkId, bidsByPunkId, listingsByPunkId});
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return NextResponse.json({error: msg}, {status: 500});
    }
}
