/**
 * Protocol reference-docs generator.
 *
 * Merges three inputs into the final API reference:
 *   1. Checked-in ABIs            app/lib/abis/<Name>.json      (signatures, events, errors)
 *   2. Mainnet deployments        contracts/deployments.mainnet.json (addresses)
 *   3. Hand-authored prose        docs/reference/_prose/<Name>.md
 *      + hand-written pages       docs/reference/_pages/**
 *
 * Outputs:
 *   docs/reference/<section>/<slug>.md   final pages (GENERATED — edit _prose/_pages)
 *   docs/reference/reference/*.md        cross-cutting indexes (access control, errors, events)
 *   app/lib/docs/manifest.json           sidebar tree + page metadata
 *   app/lib/docs/search-index.json       client-side search corpus
 *   app/public/abis/<Name>.json          ABI copies served to integrators/agents
 *   app/public/protocol-manifest.json    machine-readable protocol entry point
 *   app/public/llms.txt                  LLM orientation file
 *
 * The generator is deliberately strict: every ABI function/event/error must
 * have a prose block, every state-changing function must declare its access
 * model, and prose blocks naming unknown ABI items fail the build. Signatures
 * can never drift because they are derived, not written.
 *
 * Prose format: see docs/reference/_prose/SPEC.md.
 */
import {cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {Marked} from 'marked';
import {createHighlighter, type Highlighter} from 'shiki';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ABI_DIR = join(ROOT, 'app', 'lib', 'abis');
const PROSE_DIR = join(ROOT, 'docs', 'reference', '_prose');
const PAGES_DIR = join(ROOT, 'docs', 'reference', '_pages');
const OUT_DIR = join(ROOT, 'docs', 'reference');
const APP_DOCS_DIR = join(ROOT, 'app', 'lib', 'docs');
const APP_PUBLIC_DIR = join(ROOT, 'app', 'public');
const DEPLOYMENTS = JSON.parse(readFileSync(join(ROOT, 'contracts', 'deployments.mainnet.json'), 'utf8')) as Record<
    string,
    string | number
>;

const GENERATED_BANNER = (src: string) =>
    `<!-- GENERATED by scripts/generate-docs.ts from ${src} — do not edit this file directly. -->\n\n`;

// ── Page plan ──────────────────────────────────────────────────────────

interface ContractPage {
    name: string; // ABI + prose file name
    slug: string;
    /** Key into deployments.mainnet.json; null = address is discovered on-chain (prose explains how). */
    deploymentsKey: string | null;
}

/** Order here = sidebar order within the Contracts section. */
const CONTRACT_PAGES: ContractPage[] = [
    {name: 'PermanentCollection', slug: 'permanent-collection', deploymentsKey: 'permanentCollection'},
    {name: 'Patron', slug: 'patron', deploymentsKey: 'patron'},
    {name: 'ReturnAuctionModule', slug: 'return-auction-module', deploymentsKey: 'returnAuctionModule'},
    {name: 'ReturnAuctionEscrow', slug: 'return-auction-escrow', deploymentsKey: null},
    {name: 'PunkVault', slug: 'punk-vault', deploymentsKey: 'punkVault'},
    {name: 'LiveBidAdapter', slug: 'live-bid-adapter', deploymentsKey: 'liveBidAdapter'},
    {name: 'BuybackBurner', slug: 'buyback-burner', deploymentsKey: 'buybackBurner'},
    {name: 'VaultBurnPool', slug: 'vault-burn-pool', deploymentsKey: 'vaultBurnPool'},
    {name: 'ProtocolFeePhaseAdapter', slug: 'protocol-fee-phase-adapter', deploymentsKey: 'protocolFeePhaseAdapter'},
    {name: 'ReferralPayout', slug: 'referral-payout', deploymentsKey: 'referralPayout'},
    {name: 'PunkVaultTitleAuction', slug: 'title-auction', deploymentsKey: 'titleAuction'},
    {name: 'PCSwapContext', slug: 'pc-swap-context', deploymentsKey: 'pcSwapContext'},
    {name: 'TokenAdminPoker', slug: 'token-admin-poker', deploymentsKey: 'tokenAdminPoker'},
    {name: 'ProtocolAdmin', slug: 'protocol-admin', deploymentsKey: 'protocolAdmin'},
    {name: 'RendererRegistry', slug: 'renderer-registry', deploymentsKey: 'rendererRegistry'},
    {name: 'PermanentCollectionMosaicRenderer', slug: 'mosaic-renderer', deploymentsKey: 'renderer'},
    {name: 'PermanentCollectionProofRenderer', slug: 'proof-renderer', deploymentsKey: null},
    {name: 'PunkSvgFragmentCache', slug: 'punk-svg-fragment-cache', deploymentsKey: 'punkSvgCache'},
    {name: 'TraitIconCache', slug: 'trait-icon-cache', deploymentsKey: 'traitIconCache'},
];

/** Hand-written pages copied through from _pages/ (with {{addr:*}} substitution). */
interface HandPage {
    section: string;
    slug: string;
    file: string; // path under _pages/
}

const HAND_PAGES: HandPage[] = [
    {section: 'introduction', slug: 'overview', file: 'introduction/overview.md'},
    {section: 'introduction', slug: 'conventions', file: 'introduction/conventions.md'},
    {section: 'contracts', slug: 'the-111-token', file: 'contracts/the-111-token.md'},
    {section: 'contracts', slug: 'skim-hook', file: 'contracts/skim-hook.md'},
    {section: 'guides', slug: 'accept-the-live-bid', file: 'guides/accept-the-live-bid.md'},
    {section: 'guides', slug: 'bid-on-a-return-auction', file: 'guides/bid-on-a-return-auction.md'},
    {section: 'guides', slug: 'run-a-keeper', file: 'guides/run-a-keeper.md'},
    {section: 'guides', slug: 'swap-with-attribution', file: 'guides/swap-with-attribution.md'},
    {section: 'guides', slug: 'contribute-to-the-bid', file: 'guides/contribute-to-the-bid.md'},
    {section: 'guides', slug: 'read-collection-state', file: 'guides/read-collection-state.md'},
    {section: 'offchain', slug: 'indexer', file: 'offchain/indexer.md'},
    {section: 'offchain', slug: 'rest-api', file: 'offchain/rest-api.md'},
    {section: 'offchain', slug: 'abis-and-manifest', file: 'offchain/abis-and-manifest.md'},
];

const SECTION_TITLES: Record<string, string> = {
    introduction: 'Introduction',
    contracts: 'Contracts',
    guides: 'Guides',
    offchain: 'Off-chain',
    reference: 'Reference',
};

// ── ABI types + signature rendering ────────────────────────────────────

interface AbiParam {
    name: string;
    type: string;
    internalType?: string;
    indexed?: boolean;
    components?: AbiParam[];
}

interface AbiItem {
    type: 'function' | 'event' | 'error' | 'constructor' | 'receive' | 'fallback';
    name?: string;
    inputs?: AbiParam[];
    outputs?: AbiParam[];
    stateMutability?: 'pure' | 'view' | 'nonpayable' | 'payable';
}

function paramType(p: AbiParam): string {
    if (p.internalType) {
        // "struct Patron.Listing" → "Patron.Listing"; keep array suffixes.
        return p.internalType.replace(/^(struct|enum|contract) /, '');
    }
    return p.type;
}

function renderParams(params: AbiParam[] | undefined, withIndexed = false): string {
    if (!params || params.length === 0) return '';
    return params
        .map((p) => {
            const indexed = withIndexed && p.indexed ? ' indexed' : '';
            const name = p.name ? ` ${p.name}` : '';
            return `${paramType(p)}${indexed}${name}`;
        })
        .join(', ');
}

function functionSignature(item: AbiItem): string {
    const mut = item.stateMutability;
    const mutStr = mut === 'nonpayable' ? '' : ` ${mut}`;
    const outs = item.outputs && item.outputs.length > 0 ? ` returns (${renderParams(item.outputs)})` : '';
    return `function ${item.name}(${renderParams(item.inputs)}) external${mutStr}${outs}`;
}

function eventSignature(item: AbiItem): string {
    return `event ${item.name}(${renderParams(item.inputs, true)})`;
}

function errorSignature(item: AbiItem): string {
    return `error ${item.name}(${renderParams(item.inputs)})`;
}

/** Disambiguation key used by prose for overloads: name(type1,type2). */
function overloadKey(item: AbiItem): string {
    return `${item.name}(${(item.inputs ?? []).map((p) => p.type).join(',')})`;
}

// ── Prose parsing ──────────────────────────────────────────────────────

interface ProseBlock {
    kind: 'function' | 'event' | 'error' | 'receive';
    key: string; // name or name(types)
    access: string | null;
    body: string;
    order: number;
}

interface ProseFile {
    frontmatter: Record<string, string>;
    summary: string;
    concepts: string | null;
    blocks: ProseBlock[];
}

function parseFrontmatter(src: string): {frontmatter: Record<string, string>; body: string} {
    const m = src.match(/^---\n([\s\S]*?)\n---\n?/);
    if (!m) return {frontmatter: {}, body: src};
    const frontmatter: Record<string, string> = {};
    for (const line of m[1].split('\n')) {
        const kv = line.match(/^(\w[\w-]*):\s*(.*)$/);
        if (kv) frontmatter[kv[1]] = kv[2].trim();
    }
    return {frontmatter, body: src.slice(m[0].length)};
}

function parseProse(path: string): ProseFile {
    const {frontmatter, body} = parseFrontmatter(readFileSync(path, 'utf8'));
    // Split into segments on top-level `# ` and `## ` headings. `###`+ stay inside bodies.
    const lines = body.split('\n');
    interface Seg {
        level: number;
        heading: string;
        body: string[];
    }
    const segs: Seg[] = [];
    let cur: Seg | null = null;
    let inFence = false;
    for (const line of lines) {
        if (/^```/.test(line)) inFence = !inFence;
        const h = !inFence && line.match(/^(#{1,2}) (.+)$/);
        if (h) {
            if (cur) segs.push(cur);
            cur = {level: h[1].length, heading: h[2].trim(), body: []};
        } else if (cur) {
            cur.body.push(line);
        } else if (line.trim() !== '') {
            throw new Error(`${path}: content before the first heading: "${line}"`);
        }
    }
    if (cur) segs.push(cur);

    let summary = '';
    let concepts: string | null = null;
    const blocks: ProseBlock[] = [];
    let order = 0;
    for (const seg of segs) {
        const text = seg.body.join('\n').trim();
        if (seg.level === 1) {
            if (seg.heading === 'summary') summary = text;
            else if (seg.heading === 'concepts') concepts = text;
            else throw new Error(`${path}: unknown top-level section "# ${seg.heading}" (only summary/concepts allowed)`);
            continue;
        }
        // level 2: item block
        if (seg.heading === 'receive') {
            const {access, rest} = extractAccess(text);
            blocks.push({kind: 'receive', key: 'receive', access, body: rest, order: order++});
            continue;
        }
        const m = seg.heading.match(/^(function|event|error) (\w+)(\([\w\s,[\]]*\))?$/);
        if (!m) throw new Error(`${path}: malformed block heading "## ${seg.heading}"`);
        const kind = m[1] as ProseBlock['kind'];
        const key = m[3] ? `${m[2]}${m[3].replace(/\s+/g, '')}` : m[2];
        const {access, rest} = extractAccess(text);
        blocks.push({kind, key, access, body: rest, order: order++});
    }
    if (!summary) throw new Error(`${path}: missing "# summary" section`);
    return {frontmatter, summary, concepts, blocks};
}

function extractAccess(text: string): {access: string | null; rest: string} {
    const m = text.match(/^access:\s*(.+)\n?/);
    if (!m) return {access: null, rest: text};
    return {access: m[1].trim(), rest: text.slice(m[0].length).trim()};
}

// ── Address substitution ───────────────────────────────────────────────

function substituteTokens(text: string, context: string): string {
    return text.replace(/\{\{addr:(\w+)\}\}/g, (_, key: string) => {
        const v = DEPLOYMENTS[key];
        if (typeof v !== 'string' || !v.startsWith('0x')) {
            throw new Error(`${context}: {{addr:${key}}} does not resolve to an address in deployments.mainnet.json`);
        }
        return v;
    });
}

// ── Contract page assembly ─────────────────────────────────────────────

interface BuiltPage {
    section: string;
    slug: string;
    title: string;
    description: string;
    markdown: string; // final body (no frontmatter)
}

interface AccessRow {
    contract: string;
    slug: string;
    fn: string;
    signature: string;
    access: string;
}

interface IndexRow {
    contract: string;
    slug: string;
    name: string;
    signature: string;
    prose: string;
}

const accessRows: AccessRow[] = [];
const errorRows: IndexRow[] = [];
const eventRows: IndexRow[] = [];

function firstSentence(text: string): string {
    const flat = text.replace(/\s+/g, ' ').trim();
    // Shield abbreviation dots so "i.e." / "e.g." don't end the sentence.
    const shielded = flat.replace(/\b(i\.e|e\.g)\./gi, '$1\u0000');
    const m = shielded.match(/^.*?[.!?](?=\s|$)/);
    return (m ? m[0] : shielded).replace(/\u0000/g, '.').slice(0, 240);
}

function buildContractPage(page: ContractPage): BuiltPage {
    const abiPath = join(ABI_DIR, `${page.name}.json`);
    const prosePath = join(PROSE_DIR, `${page.name}.md`);
    if (!existsSync(abiPath)) throw new Error(`missing ABI: ${abiPath}`);
    if (!existsSync(prosePath)) throw new Error(`missing prose supplement: ${prosePath}`);
    const abi = JSON.parse(readFileSync(abiPath, 'utf8')) as AbiItem[];
    const prose = parseProse(prosePath);

    // Index ABI items; detect overloads.
    const fns = abi.filter((i) => i.type === 'function');
    const events = abi.filter((i) => i.type === 'event');
    const errors = abi.filter((i) => i.type === 'error');
    const hasReceive = abi.some((i) => i.type === 'receive');
    const nameCounts = new Map<string, number>();
    for (const f of fns) nameCounts.set(f.name!, (nameCounts.get(f.name!) ?? 0) + 1);

    const proseFor = new Map<string, ProseBlock>();
    for (const b of prose.blocks) {
        const mapKey = `${b.kind}:${b.key}`;
        if (proseFor.has(mapKey)) throw new Error(`${prosePath}: duplicate block ${mapKey}`);
        proseFor.set(mapKey, b);
    }

    const problems: string[] = [];
    const usedBlocks = new Set<string>();

    function lookup(kind: ProseBlock['kind'], item: AbiItem): ProseBlock | null {
        const overload = overloadKey(item);
        const byOverload = proseFor.get(`${kind}:${overload}`);
        if (byOverload) {
            usedBlocks.add(`${kind}:${overload}`);
            return byOverload;
        }
        if ((nameCounts.get(item.name!) ?? 0) > 1 && kind === 'function') {
            problems.push(`overloaded function ${item.name} needs a "## function ${overload}" block`);
            return null;
        }
        const byName = proseFor.get(`${kind}:${item.name!}`);
        if (byName) {
            usedBlocks.add(`${kind}:${item.name!}`);
            return byName;
        }
        problems.push(`missing "## ${kind} ${item.name}" block`);
        return null;
    }

    // Partition + order functions: write fns in prose order, read fns alphabetical.
    const writeFns: {item: AbiItem; block: ProseBlock | null}[] = [];
    const readFns: {item: AbiItem; block: ProseBlock | null}[] = [];
    for (const f of fns) {
        const block = lookup('function', f);
        const isWrite = f.stateMutability === 'nonpayable' || f.stateMutability === 'payable';
        if (isWrite && block && !block.access) {
            problems.push(`state-changing function ${f.name} has no "access:" line`);
        }
        (isWrite ? writeFns : readFns).push({item: f, block});
    }
    writeFns.sort((a, b) => (a.block?.order ?? 1e9) - (b.block?.order ?? 1e9));
    readFns.sort((a, b) => a.item.name!.localeCompare(b.item.name!));
    events.sort((a, b) => a.name!.localeCompare(b.name!));
    errors.sort((a, b) => a.name!.localeCompare(b.name!));

    let receiveBlock: ProseBlock | null = null;
    if (hasReceive) {
        receiveBlock = proseFor.get('receive:receive') ?? null;
        if (receiveBlock) usedBlocks.add('receive:receive');
        else problems.push('missing "## receive" block for the receive() function');
        if (receiveBlock && !receiveBlock.access) problems.push('receive() block has no "access:" line');
    }

    const eventBlocks = events.map((e) => ({item: e, block: lookup('event', e)}));
    const errorBlocks = errors.map((e) => ({item: e, block: lookup('error', e)}));

    for (const key of proseFor.keys()) {
        if (!usedBlocks.has(key)) problems.push(`prose block "${key}" matches nothing in the ABI`);
    }
    if (problems.length > 0) {
        throw new Error(`${page.name}: prose/ABI mismatch\n  - ${problems.join('\n  - ')}`);
    }

    // Assemble markdown.
    const address = page.deploymentsKey ? (DEPLOYMENTS[page.deploymentsKey] as string) : null;
    const parts: string[] = [];
    parts.push(`# ${page.name}`);
    if (address) {
        parts.push(
            `\`${address}\` · [view on evm.now](https://evm.now/address/${address}?chainId=1) · deployed at block ${DEPLOYMENTS.deployBlock}`,
        );
    }
    parts.push(prose.summary);
    if (prose.concepts) {
        parts.push(`## Concepts`);
        parts.push(prose.concepts);
    }

    if (writeFns.length > 0 || hasReceive) {
        parts.push(`## Write functions`);
        for (const {item, block} of writeFns) {
            parts.push(`### ${item.name}`);
            parts.push('```solidity\n' + functionSignature(item) + '\n```');
            parts.push(`**Access:** ${block!.access}`);
            if (block!.body) parts.push(block!.body);
            accessRows.push({
                contract: page.name,
                slug: page.slug,
                fn: item.name!,
                signature: functionSignature(item),
                access: block!.access!,
            });
        }
        if (hasReceive && receiveBlock) {
            parts.push(`### receive`);
            parts.push('```solidity\nreceive() external payable\n```');
            parts.push(`**Access:** ${receiveBlock.access}`);
            if (receiveBlock.body) parts.push(receiveBlock.body);
            accessRows.push({
                contract: page.name,
                slug: page.slug,
                fn: 'receive',
                signature: 'receive() external payable',
                access: receiveBlock.access!,
            });
        }
    }

    if (readFns.length > 0) {
        parts.push(`## Read functions`);
        for (const {item, block} of readFns) {
            parts.push(`### ${item.name}`);
            parts.push('```solidity\n' + functionSignature(item) + '\n```');
            if (block!.body) parts.push(block!.body);
        }
    }

    if (eventBlocks.length > 0) {
        parts.push(`## Events`);
        for (const {item, block} of eventBlocks) {
            parts.push(`### ${item.name}`);
            parts.push('```solidity\n' + eventSignature(item) + '\n```');
            if (block!.body) parts.push(block!.body);
            eventRows.push({
                contract: page.name,
                slug: page.slug,
                name: item.name!,
                signature: eventSignature(item),
                prose: firstSentence(block!.body),
            });
        }
    }

    if (errorBlocks.length > 0) {
        parts.push(`## Errors`);
        for (const {item, block} of errorBlocks) {
            parts.push(`**\`${errorSignature(item).replace(/^error /, '')}\`**`);
            parts.push(block!.body);
            errorRows.push({
                contract: page.name,
                slug: page.slug,
                name: item.name!,
                signature: errorSignature(item),
                prose: firstSentence(block!.body),
            });
        }
    }

    const markdown = substituteTokens(parts.join('\n\n') + '\n', prosePath);
    return {
        section: 'contracts',
        slug: page.slug,
        title: prose.frontmatter.title || page.name,
        description: firstSentence(prose.summary),
        markdown,
    };
}

// ── Hand pages ─────────────────────────────────────────────────────────

function buildHandPage(hp: HandPage): BuiltPage {
    const path = join(PAGES_DIR, hp.file);
    if (!existsSync(path)) throw new Error(`missing hand-written page: ${path}`);
    const {frontmatter, body} = parseFrontmatter(readFileSync(path, 'utf8'));
    if (!frontmatter.title) throw new Error(`${path}: frontmatter needs a title`);
    const markdown = substituteTokens(body.trim() + '\n', path);
    const h1 = markdown.match(/^# (.+)$/m);
    return {
        section: hp.section,
        slug: hp.slug,
        title: frontmatter.title,
        description: frontmatter.description || (h1 ? h1[1] : frontmatter.title),
        markdown,
    };
}

// ── Generated pages: addresses + cross-cutting indexes ─────────────────

const EXTERNAL_ADDRESSES: {label: string; key: string}[] = [
    {label: 'The $111 token (ArtCoinsToken)', key: 'token'},
    {label: 'Skim hook (ArtCoinsHookSkimFee)', key: 'hook'},
    {label: 'Conversion locker (LP positions)', key: 'locker'},
    {label: 'MEV module (ArtCoinsMevLinearSkim)', key: 'mevModule'},
    {label: 'PunksData (sealed trait dataset)', key: 'punksData'},
];

function buildAddressesPage(): BuiltPage {
    const rows: string[] = [];
    rows.push('| Contract | Address | Docs |');
    rows.push('| --- | --- | --- |');
    for (const p of CONTRACT_PAGES) {
        if (!p.deploymentsKey) continue;
        const addr = DEPLOYMENTS[p.deploymentsKey] as string;
        rows.push(
            `| ${p.name} | [\`${addr}\`](https://evm.now/address/${addr}?chainId=1) | [reference](/docs/contracts/${p.slug}) |`,
        );
    }
    const ext: string[] = [];
    ext.push('| Contract | Address |');
    ext.push('| --- | --- |');
    for (const e of EXTERNAL_ADDRESSES) {
        const addr = DEPLOYMENTS[e.key] as string;
        if (typeof addr !== 'string') continue;
        ext.push(`| ${e.label} | [\`${addr}\`](https://evm.now/address/${addr}?chainId=1) |`);
    }
    const md = [
        '# Addresses',
        `Every protocol contract on Ethereum mainnet (chain id ${DEPLOYMENTS.chainId}), deployed at block ${DEPLOYMENTS.deployBlock}. All contracts are immutable and source-verified.`,
        rows.join('\n'),
        '## Launch-stack and external contracts',
        ext.join('\n'),
        `The canonical V4 pool id is \`${DEPLOYMENTS.canonicalPoolId}\`.`,
        'A machine-readable version of this table (addresses + ABI + docs links) is served at [`/protocol-manifest.json`](/protocol-manifest.json).',
    ].join('\n\n');
    return {
        section: 'introduction',
        slug: 'addresses',
        title: 'Addresses',
        description: 'Every protocol contract on Ethereum mainnet, with ABI and reference links.',
        markdown: md + '\n',
    };
}

function buildAccessControlPage(): BuiltPage {
    const parts: string[] = ['# Access control'];
    parts.push(
        'Every state-changing function in the protocol and who may call it. Generated from the per-contract references; the per-function pages carry the full behavior.',
    );
    let currentContract = '';
    const rows: string[] = [];
    for (const r of accessRows) {
        if (r.contract !== currentContract) {
            if (rows.length) {
                parts.push(rows.join('\n'));
                rows.length = 0;
            }
            currentContract = r.contract;
            parts.push(`## ${r.contract}`);
            rows.push('| Function | Access |');
            rows.push('| --- | --- |');
        }
        rows.push(`| [\`${r.fn}\`](/docs/contracts/${r.slug}#${anchor(r.fn)}) | ${r.access} |`);
    }
    if (rows.length) parts.push(rows.join('\n'));
    return {
        section: 'reference',
        slug: 'access-control',
        title: 'Access control',
        description: 'Every state-changing function and who may call it.',
        markdown: parts.join('\n\n') + '\n',
    };
}

function buildErrorsPage(): BuiltPage {
    const parts: string[] = ['# Errors index'];
    parts.push('Every custom error the protocol can revert with, its contract, and the condition that raises it.');
    const sorted = [...errorRows].sort((a, b) => a.name.localeCompare(b.name) || a.contract.localeCompare(b.contract));
    for (const r of sorted) {
        parts.push(`**\`${r.name}\`** · [${r.contract}](/docs/contracts/${r.slug}#errors)\\\n${r.prose}`);
    }
    return {
        section: 'reference',
        slug: 'errors',
        title: 'Errors index',
        description: 'Every custom error, its contract, and the condition that raises it.',
        markdown: parts.join('\n\n') + '\n',
    };
}

function buildEventsPage(): BuiltPage {
    const parts: string[] = ['# Events index'];
    parts.push('Every event the protocol emits, grouped by contract. Signatures and field meanings live on the per-contract pages.');
    let currentContract = '';
    for (const r of eventRows) {
        if (r.contract !== currentContract) {
            currentContract = r.contract;
            parts.push(`## ${r.contract}`);
        }
        parts.push(`**[\`${r.name}\`](/docs/contracts/${r.slug}#${anchor(r.name)})** · ${r.prose}`);
    }
    return {
        section: 'reference',
        slug: 'events',
        title: 'Events index',
        description: 'Every event the protocol emits, grouped by contract.',
        markdown: parts.join('\n\n') + '\n',
    };
}

// ── Anchors (must match the app renderer's slugify) ────────────────────

function anchor(heading: string): string {
    return heading
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '')
        .trim()
        .replace(/\s+/g, '-');
}

// ── Markdown → HTML (pre-rendered at generation time) ──────────────────
//
// The app's root layout is force-dynamic, so docs pages render at request
// time inside serverless functions where reading ../docs/reference off the
// filesystem is not an option. The generator therefore pre-renders every
// page to highlighted HTML and ships it as an importable JSON module; the
// app carries no markdown or highlighting dependency at all.

interface TocEntry {
    depth: number;
    text: string;
    id: string;
}

interface RenderedPage {
    section: string;
    slug: string;
    title: string;
    description: string;
    html: string;
    toc: TocEntry[];
}

function escapeHtml(s: string): string {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function renderPageHtml(hl: Highlighter, page: BuiltPage): RenderedPage {
    const toc: TocEntry[] = [];
    const loadedLangs = new Set(hl.getLoadedLanguages());
    const marked = new Marked({gfm: true});
    marked.use({
        renderer: {
            heading({tokens, depth, text}) {
                const inline = this.parser.parseInline(tokens);
                const id = anchor(text);
                if (depth === 2 || depth === 3) toc.push({depth, text, id});
                return `<h${depth} id="${id}"><a class="doc-anchor" href="#${id}">${inline}</a></h${depth}>\n`;
            },
            code({text, lang}) {
                const language = lang && loadedLangs.has(lang) ? lang : null;
                const body = language
                    ? hl.codeToHtml(text, {lang: language, theme: 'github-light'})
                    : `<pre class="shiki"><code>${escapeHtml(text)}</code></pre>`;
                const langTag = lang ? `<span class="doc-code-lang">${escapeHtml(lang)}</span>` : '';
                return `<div class="doc-code">${langTag}<button class="doc-copy" type="button" aria-label="Copy code">copy</button>${body}</div>\n`;
            },
        },
    });
    const html = marked.parse(page.markdown, {async: false}) as string;
    return {
        section: page.section,
        slug: page.slug,
        title: page.title,
        description: page.description,
        html,
        toc,
    };
}

// ── Search index ───────────────────────────────────────────────────────

interface SearchEntry {
    path: string; // /docs/<section>/<slug>
    page: string; // page title
    heading: string;
    anchor: string;
    text: string;
}

function stripMarkdown(md: string): string {
    return md
        .replace(/```[\s\S]*?```/g, ' ')
        .replace(/`([^`]*)`/g, '$1')
        .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
        .replace(/^#+ /gm, '')
        .replace(/[*_>|]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}

function indexPage(page: BuiltPage): SearchEntry[] {
    const path = `/docs/${page.section}/${page.slug}`;
    const entries: SearchEntry[] = [];
    const segments = page.markdown.split(/^(?=#{1,3} )/m);
    for (const seg of segments) {
        const h = seg.match(/^(#{1,3}) (.+)\n/);
        const heading = h ? h[2].trim() : page.title;
        const body = stripMarkdown(h ? seg.slice(h[0].length) : seg);
        if (!body && !h) continue;
        entries.push({
            path,
            page: page.title,
            heading,
            anchor: h && h[1].length > 1 ? anchor(heading) : '',
            text: body.slice(0, 300),
        });
    }
    return entries;
}

// ── Main ───────────────────────────────────────────────────────────────

async function main() {
    const pages: BuiltPage[] = [];

    // Hand-written intro pages first (overview before addresses before conventions).
    const introPages = HAND_PAGES.filter((h) => h.section === 'introduction');
    pages.push(buildHandPage(introPages.find((h) => h.slug === 'overview')!));
    pages.push(buildAddressesPage());
    pages.push(buildHandPage(introPages.find((h) => h.slug === 'conventions')!));

    // Contracts: hand-written token + hook pages lead, then the generated references.
    for (const hp of HAND_PAGES.filter((h) => h.section === 'contracts')) pages.push(buildHandPage(hp));
    for (const cp of CONTRACT_PAGES) pages.push(buildContractPage(cp));

    for (const hp of HAND_PAGES.filter((h) => h.section === 'guides')) pages.push(buildHandPage(hp));
    for (const hp of HAND_PAGES.filter((h) => h.section === 'offchain')) pages.push(buildHandPage(hp));

    pages.push(buildAccessControlPage());
    pages.push(buildErrorsPage());
    pages.push(buildEventsPage());

    // Write final markdown tree (wipe generated sections, keep _prose/_pages).
    for (const section of Object.keys(SECTION_TITLES)) {
        rmSync(join(OUT_DIR, section), {recursive: true, force: true});
        mkdirSync(join(OUT_DIR, section), {recursive: true});
    }
    for (const p of pages) {
        const banner = GENERATED_BANNER(
            p.section === 'contracts' && CONTRACT_PAGES.some((c) => c.slug === p.slug)
                ? `_prose/ + app/lib/abis`
                : `_pages/ + app/lib/abis`,
        );
        writeFileSync(join(OUT_DIR, p.section, `${p.slug}.md`), banner + p.markdown);
    }

    // Manifest (sidebar order = insertion order above).
    const manifest = {
        title: 'Protocol reference',
        sections: Object.entries(SECTION_TITLES).map(([id, title]) => ({
            id,
            title,
            items: pages
                .filter((p) => p.section === id)
                .map((p) => ({title: p.title, slug: p.slug, path: `/docs/${id}/${p.slug}`, description: p.description})),
        })),
    };
    mkdirSync(APP_DOCS_DIR, {recursive: true});
    writeFileSync(join(APP_DOCS_DIR, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

    // Pre-rendered HTML content module (imported by the app's /docs pages).
    const hl = await createHighlighter({
        themes: ['github-light'],
        langs: ['solidity', 'typescript', 'javascript', 'bash', 'json', 'graphql'],
    });
    const content: Record<string, RenderedPage> = {};
    for (const p of pages) {
        content[`${p.section}/${p.slug}`] = renderPageHtml(hl, p);
    }
    writeFileSync(join(APP_DOCS_DIR, 'content.json'), JSON.stringify(content) + '\n');

    // Search index (served statically, fetched lazily by the client).
    const search = pages.flatMap(indexPage);
    writeFileSync(join(APP_PUBLIC_DIR, 'docs-search-index.json'), JSON.stringify(search) + '\n');

    // Public ABIs.
    const publicAbiDir = join(APP_PUBLIC_DIR, 'abis');
    rmSync(publicAbiDir, {recursive: true, force: true});
    mkdirSync(publicAbiDir, {recursive: true});
    for (const f of readdirSync(ABI_DIR)) {
        if (f.endsWith('.json')) cpSync(join(ABI_DIR, f), join(publicAbiDir, f));
    }

    // Protocol manifest.
    const protocolManifest = {
        name: 'PERMANENT COLLECTION',
        chainId: DEPLOYMENTS.chainId,
        deployBlock: DEPLOYMENTS.deployBlock,
        canonicalPoolId: DEPLOYMENTS.canonicalPoolId,
        docs: '/docs',
        llms: '/llms.txt',
        contracts: Object.fromEntries(
            CONTRACT_PAGES.filter((p) => p.deploymentsKey).map((p) => {
                const built = pages.find((x) => x.section === 'contracts' && x.slug === p.slug)!;
                return [
                    p.name,
                    {
                        address: DEPLOYMENTS[p.deploymentsKey!],
                        abi: `/abis/${p.name}.json`,
                        docs: `/docs/contracts/${p.slug}`,
                        role: built.description,
                    },
                ];
            }),
        ),
        external: Object.fromEntries(
            EXTERNAL_ADDRESSES.filter((e) => typeof DEPLOYMENTS[e.key] === 'string').map((e) => [
                e.key,
                {address: DEPLOYMENTS[e.key], label: e.label},
            ]),
        ),
    };
    writeFileSync(join(APP_PUBLIC_DIR, 'protocol-manifest.json'), JSON.stringify(protocolManifest, null, 2) + '\n');

    // llms.txt
    const llms: string[] = [];
    llms.push('# PERMANENT COLLECTION');
    llms.push('');
    llms.push(
        '> An immutable on-chain protocol on Ethereum mainnet that builds a permanent collection of CryptoPunks via full-trait coverage: a global ETH live bid any eligible Punk owner can accept, a 72-hour return auction deciding each accepted Punk, and the $111 token whose trading fees fund the loop. All contracts are deployed, immutable, and source-verified.',
    );
    llms.push('');
    llms.push('Machine-readable addresses + ABIs: /protocol-manifest.json (ABIs under /abis/). Paths are relative to this site.');
    llms.push('');
    for (const section of manifest.sections) {
        llms.push(`## ${section.title}`);
        llms.push('');
        for (const item of section.items) {
            llms.push(`- [${item.title}](${item.path}): ${item.description}`);
        }
        llms.push('');
    }
    writeFileSync(join(APP_PUBLIC_DIR, 'llms.txt'), llms.join('\n'));

    console.log(
        `Generated ${pages.length} pages, ${search.length} search entries, ${accessRows.length} access rows, ${errorRows.length} errors, ${eventRows.length} events.`,
    );
}

main().catch((e: unknown) => {
    console.error(e instanceof Error ? e.message : e);
    process.exit(1);
});
