/**
 * Read forge build artifacts, extract ABIs, and emit JSON files consumed by
 * the indexer and frontend.
 *
 * V4 + hook-redesign protocol surface:
 *   Permanent core:
 *     PermanentCollection, PunkVault, Patron, ReturnAuctionModule,
 *     BuybackBurner, ProtocolAdmin
 *   Fee infrastructure (claim-token recipients from the 3-leg hook split):
 *     LiveBidAdapter, VaultBurnPool,
 *     ProtocolFeePhaseAdapter, ReferralPayout
 *   Composability surface (dormant at launch; ready for Design B):
 *     PCSwapContext, TokenAdminPoker
 *   Demo / Design B (NOT bound at launch):
 *     UnipegDispatcher
 *   Renderer + auxiliary:
 *     PermanentCollectionMosaicRenderer, RendererRegistry,
 *     PunkSvgFragmentCache, TraitIconCache, PunkVaultTitleAuction
 *   From the artcoins submodule:
 *     ArtCoinsHookSkimFee  (for flushReferral + accruedReferral reads)
 */
import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const OUT_DIR = join(ROOT, 'contracts', 'out');
const INDEXER_ABI_DIR = join(ROOT, 'indexer', 'abis');
const APP_ABI_DIR = join(ROOT, 'app', 'lib', 'abis');

const CONTRACTS = [
    // Permanent core
    'PermanentCollection',
    'PunkVault',
    'Patron',
    'ReturnAuctionModule',
    'BuybackBurner',
    'ProtocolAdmin',
    // Fee infrastructure
    'LiveBidAdapter',
    'VaultBurnPool',
    'ProtocolFeePhaseAdapter',
    'ReferralPayout',
    // Composability surface
    'PCSwapContext',
    'TokenAdminPoker',
    // Demo / Design B
    'UnipegDispatcher',
    // Renderer + auxiliary
    'PunkVaultTitleAuction',
    'RendererRegistry',
    'PermanentCollectionMosaicRenderer',
    'PunkSvgFragmentCache',
    'TraitIconCache',
] as const;

const EXTERNAL = [
    {name: 'CryptoPunksMarket', source: 'ICryptoPunksMarket'},
    {name: 'CryptoPunksData', source: 'ICryptoPunksData'},
    {name: 'PunksData', source: 'IPunksData'},
    // The hook lives in the artcoins submodule. forge build emits its
    // artifact at out/ArtCoinsHookSkimFee.sol/ArtCoinsHookSkimFee.json
    // alongside our own contracts, so it goes through the same path.
    {name: 'ArtCoinsHookSkimFee', source: 'ArtCoinsHookSkimFee'},
] as const;

function readAbi(sourceName: string, contractName?: string): unknown {
    const path = join(OUT_DIR, `${sourceName}.sol`, `${contractName ?? sourceName}.json`);
    const j = JSON.parse(readFileSync(path, 'utf8'));
    return j.abi;
}

function writeAbisTo(targetDir: string) {
    if (!existsSync(targetDir)) {
        mkdirSync(targetDir, {recursive: true});
    }
    // Emit JSON for runtime consumption.
    for (const c of CONTRACTS) {
        writeFileSync(join(targetDir, `${c}.json`), JSON.stringify(readAbi(c), null, 2));
    }
    for (const e of EXTERNAL) {
        writeFileSync(join(targetDir, `${e.name}.json`), JSON.stringify(readAbi(e.source, e.source), null, 2));
    }
    // Emit TS-with-`as const` so downstream tools (Ponder, wagmi) can narrow
    // event/function names from the literal types.
    for (const c of CONTRACTS) {
        const body = `// AUTOGENERATED by scripts/generate-abis.ts — do not edit.\nexport const abi = ${JSON.stringify(readAbi(c), null, 2)} as const;\n`;
        writeFileSync(join(targetDir, `${c}.ts`), body);
    }
    for (const e of EXTERNAL) {
        const body = `// AUTOGENERATED by scripts/generate-abis.ts — do not edit.\nexport const abi = ${JSON.stringify(readAbi(e.source, e.source), null, 2)} as const;\n`;
        writeFileSync(join(targetDir, `${e.name}.ts`), body);
    }
    console.log(`Wrote ${CONTRACTS.length + EXTERNAL.length} ABIs (json+ts) to ${targetDir}`);
}

writeAbisTo(INDEXER_ABI_DIR);
writeAbisTo(APP_ABI_DIR);
