/**
 * Snapshot the canonical trait taxonomy + per-Punk masks from the live
 * PunksData contract (`punksdata.eth`) into TypeScript modules the frontend
 * can import without an RPC round-trip.
 *
 * Outputs:
 *   - app/lib/categories.ts   (111 trait entries, grouped by kind)
 *   - app/lib/punkMasks.ts    (10,000 trait masks + derived RARITY)
 *
 * Both files are autogenerated and overwritten on each run. The script
 * verifies the live contract's `datasetHash()` matches the value pinned in
 * `PermanentCollection.EXPECTED_DATASET_HASH` and aborts if it doesn't.
 */
import {writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createPublicClient, http, parseAbi, type PublicClient} from 'viem';
import {mainnet} from 'viem/chains';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
// The frontend lib lives at app/lib (the legacy app/src/lib tree was removed
// in the frontend rewrite). Generated taxonomy modules land here so the app
// can `import {RARITY} from '@/lib/punkMasks'` without an RPC round-trip.
const APP_LIB = join(ROOT, 'app', 'lib');

const PUNKS_DATA = '0x9cF9C8eA737A7d5157d3F4282aCe30880a7A117C' as const;
const EXPECTED_DATASET_HASH =
    '0x92117ce6cb6bb70f9ffb9bf51ebbca6a84eae10e70639295d9c4a07958cd1f68' as const;
const TOTAL_TRAITS = 111;
const TOTAL_PUNKS = 10_000;

// Kind enum on PunksData. 0..3 corresponds to:
//   0 HeadVariant, 1 NormalizedType, 2 AttributeCount, 3 Accessory
const KIND_NAMES = ['headVariant', 'normalizedType', 'attributeCount', 'accessory'] as const;
type Kind = (typeof KIND_NAMES)[number];

const PUNKS_DATA_ABI = parseAbi([
    'function traitName(uint16 traitId) view returns (string)',
    'function traitKind(uint16 traitId) view returns (uint8)',
    'function traitMaskOf(uint16 punkId) view returns (uint256)',
    'function datasetHash() view returns (bytes32)',
    'function traitCount() view returns (uint16)',
]);

async function main() {
    const rpcUrl = process.env.MAINNET_RPC_URL || 'https://ethereum.publicnode.com';
    const client = createPublicClient({chain: mainnet, transport: http(rpcUrl, {batch: true})});

    // --- Sanity: traitCount + datasetHash ---
    const [traitCountResult, datasetHashResult] = await client.multicall({
        contracts: [
            {address: PUNKS_DATA, abi: PUNKS_DATA_ABI, functionName: 'traitCount'},
            {address: PUNKS_DATA, abi: PUNKS_DATA_ABI, functionName: 'datasetHash'},
        ],
        allowFailure: false,
    });
    if (Number(traitCountResult) !== TOTAL_TRAITS) {
        throw new Error(`traitCount mismatch: chain=${traitCountResult}, expected ${TOTAL_TRAITS}`);
    }
    if ((datasetHashResult as string).toLowerCase() !== EXPECTED_DATASET_HASH.toLowerCase()) {
        throw new Error(
            `datasetHash mismatch: chain=${datasetHashResult}, expected ${EXPECTED_DATASET_HASH}`,
        );
    }
    console.log(`PunksData OK: traitCount=${traitCountResult}, datasetHash=${datasetHashResult}`);

    // --- Trait names + kinds (111 × 2 = 222 calls) ---
    console.log('Snapshotting trait names + kinds...');
    const traits = await fetchTraits(client);
    writeCategoriesFile(traits);
    console.log(`  wrote ${join(APP_LIB, 'categories.ts')}`);

    // --- Per-Punk masks (10,000 calls) ---
    console.log('Snapshotting trait masks for all 10,000 Punks...');
    const masks = await fetchMasks(client);
    writeMasksFile(masks);
    console.log(`  wrote ${join(APP_LIB, 'punkMasks.ts')}`);

    console.log('done.');
}

interface TraitRow {
    bit: number;
    name: string;
    kind: Kind;
}

async function fetchTraits(client: PublicClient): Promise<TraitRow[]> {
    const calls = [];
    for (let i = 0; i < TOTAL_TRAITS; i++) {
        calls.push({
            address: PUNKS_DATA,
            abi: PUNKS_DATA_ABI,
            functionName: 'traitName',
            args: [i],
        } as const);
        calls.push({
            address: PUNKS_DATA,
            abi: PUNKS_DATA_ABI,
            functionName: 'traitKind',
            args: [i],
        } as const);
    }
    const results = await client.multicall({contracts: calls, allowFailure: false});
    const out: TraitRow[] = [];
    for (let i = 0; i < TOTAL_TRAITS; i++) {
        const name = results[i * 2] as string;
        const kindIdx = Number(results[i * 2 + 1]);
        const kind = KIND_NAMES[kindIdx];
        if (!kind) throw new Error(`bit ${i}: unknown kind ${kindIdx}`);
        out.push({bit: i, name, kind});
    }
    return out;
}

async function fetchMasks(client: PublicClient): Promise<bigint[]> {
    const BATCH = 500;
    const out = new Array<bigint>(TOTAL_PUNKS);
    for (let start = 0; start < TOTAL_PUNKS; start += BATCH) {
        const end = Math.min(start + BATCH, TOTAL_PUNKS);
        const calls = [];
        for (let id = start; id < end; id++) {
            calls.push({
                address: PUNKS_DATA,
                abi: PUNKS_DATA_ABI,
                functionName: 'traitMaskOf',
                args: [id],
            } as const);
        }
        const results = await client.multicall({contracts: calls, allowFailure: false});
        for (let i = 0; i < results.length; i++) {
            out[start + i] = results[i] as bigint;
        }
        if (start % 2_000 === 0) console.log(`  ${start}/${TOTAL_PUNKS}`);
    }
    return out;
}

function writeCategoriesFile(traits: TraitRow[]) {
    const punkTypes = traits.filter((t) => t.kind === 'normalizedType').map((t) => t.name);
    const headVariants = traits.filter((t) => t.kind === 'headVariant').map((t) => t.name);
    const countBuckets = traits.filter((t) => t.kind === 'attributeCount').map((t) => t.name);
    const accessoryOrder = traits.filter((t) => t.kind === 'accessory').map((t) => t.name);

    const lines: string[] = [];
    lines.push('// AUTOGENERATED by scripts/snapshot-punksdata.ts — do not edit by hand.');
    lines.push('// Snapshotted from PunksData at 0x9cF9C8eA737A7d5157d3F4282aCe30880a7A117C.');
    lines.push("export type CategoryGroup = 'normalizedType' | 'headVariant' | 'attributeCount' | 'accessory';");
    lines.push('export interface Category { bit: number; name: string; group: CategoryGroup; }');
    lines.push('');
    lines.push(`export const PUNK_TYPES = ${JSON.stringify(punkTypes)} as const;`);
    lines.push(`export const HEAD_VARIANTS = ${JSON.stringify(headVariants)} as const;`);
    lines.push(`export const COUNT_BUCKETS = ${JSON.stringify(countBuckets)} as const;`);
    lines.push(`export const ACCESSORY_ORDER = ${JSON.stringify(accessoryOrder)} as const;`);
    lines.push('');
    lines.push(`export const TOTAL_CATEGORIES = ${TOTAL_TRAITS};`);
    lines.push(`export const TOTAL_PUNKS = ${TOTAL_PUNKS};`);
    lines.push('');
    lines.push('export const CATEGORIES: Category[] = [');
    for (const t of traits) {
        lines.push(`    { bit: ${t.bit}, name: ${JSON.stringify(t.name)}, group: ${JSON.stringify(t.kind)} },`);
    }
    lines.push('];');
    lines.push('');

    writeFileSync(join(APP_LIB, 'categories.ts'), lines.join('\n'));
}

function writeMasksFile(masks: bigint[]) {
    const rarity = new Array<number>(TOTAL_TRAITS).fill(0);
    for (const m of masks) {
        for (let bit = 0; bit < TOTAL_TRAITS; bit++) {
            if ((m >> BigInt(bit)) & 1n) rarity[bit]!++;
        }
    }

    const lines: string[] = [];
    lines.push('// AUTOGENERATED by scripts/snapshot-punksdata.ts — do not edit by hand.');
    lines.push('// 10,000 trait masks indexed by Punk id (0..9999). Values are 111-bit hex.');
    lines.push('export const PUNK_MASKS: readonly bigint[] = [');
    for (const m of masks) lines.push(`    0x${m.toString(16)}n,`);
    lines.push('] as const;');
    lines.push('');
    lines.push(`export const RARITY: readonly number[] = ${JSON.stringify(rarity)};`);
    lines.push('');

    writeFileSync(join(APP_LIB, 'punkMasks.ts'), lines.join('\n'));
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
