#!/usr/bin/env tsx
/**
 * sync-indexer-env.ts
 * ---------------------------------------------------------------------------
 * Populates `indexer/.env.local` from `contracts/deployments.json` so the
 * Ponder indexer can index a local fork deploy — the indexer counterpart to
 * the app-env sync that `start-dev-fork.sh` already does.
 *
 * Run it AFTER `pnpm dev:up` (which forks, deploys, and writes
 * deployments.json), THEN start the indexer:
 *
 *   pnpm dev:up                      # fork + deploy + app
 *   pnpm tsx scripts/sync-indexer-env.ts
 *   pnpm --filter indexer dev        # Ponder → GraphQL at :42069
 *
 * The app's live adapter reads the indexer at INDEXER_URL (default
 * http://127.0.0.1:42069), so once Ponder is up the local site renders the
 * full LIVE/deployed state against the fork.
 *
 * RPC port: defaults to 8545 (the standard fork port); override with
 *   FORK_RPC_PORT=8645 pnpm tsx scripts/sync-indexer-env.ts
 */
import {existsSync, readFileSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {CANONICAL_POOL_ID_KEY, INDEXER_ADDRESS_MAP as ADDRESS_MAP} from './lib/indexer-addresses';

const ROOT = process.cwd();
const DEPLOYMENTS = join(ROOT, 'contracts', 'deployments.json');
const OUT = join(ROOT, 'indexer', '.env.local');

function main() {
    if (!existsSync(DEPLOYMENTS)) {
        console.error(
            `\n✗ No contracts/deployments.json. Run \`pnpm dev:up\` first (fork + deploy), then re-run this.\n`,
        );
        process.exit(1);
    }
    const d = JSON.parse(readFileSync(DEPLOYMENTS, 'utf8')) as Record<string, unknown>;
    const chainId = Number(d.chainId ?? 1);
    const deployBlock = String(d.deployBlock ?? 0);
    const port = process.env.FORK_RPC_PORT ?? '8545';
    const rpc = `http://127.0.0.1:${port}`;

    // A forked-mainnet anvil keeps chainId 1; a bare anvil is 31337. Ponder's
    // config branches on PONDER_NETWORK (mainnet→chainId 1, anvil→31337) — so
    // point the matching network at the local fork RPC.
    const network = chainId === 31337 ? 'anvil' : 'mainnet';
    const rpcVar = chainId === 31337 ? 'PONDER_RPC_URL_31337' : 'PONDER_RPC_URL_1';

    const lines: string[] = [
        '# Generated by scripts/sync-indexer-env.ts from contracts/deployments.json.',
        '# Points Ponder at the local fork so the app can render the live state.',
        `PONDER_NETWORK=${network}`,
        `${rpcVar}=${rpc}`,
        `START_BLOCK=${deployBlock}`,
    ];
    const missing: string[] = [];
    for (const [envName, key] of ADDRESS_MAP) {
        const v = d[key];
        if (typeof v === 'string' && /^0x[0-9a-fA-F]{40}$/.test(v)) {
            lines.push(`${envName}=${v}`);
        } else {
            missing.push(`${envName} (key: ${key})`);
        }
    }
    // Canonical pool id (bytes32, not an address — handled outside the map).
    // Gates the SkimSplit volume handler to the canonical pool.
    const poolId = d[CANONICAL_POOL_ID_KEY];
    if (typeof poolId === 'string' && /^0x[0-9a-fA-F]{64}$/.test(poolId)) {
        lines.push(`CANONICAL_POOL_ID=${poolId}`);
    } else {
        missing.push(`CANONICAL_POOL_ID (key: ${CANONICAL_POOL_ID_KEY})`);
    }
    writeFileSync(OUT, lines.join('\n') + '\n');

    console.log(`\n✓ Wrote indexer/.env.local (chainId ${chainId}, network ${network}, startBlock ${deployBlock}).`);
    console.log(`  Next: pnpm --filter indexer dev   # Ponder → http://127.0.0.1:42069`);
    if (missing.length) {
        console.log('\n  ⚠ missing in deployments.json (left unset):');
        for (const m of missing) console.log(`    - ${m}`);
    }
    console.log('');
}

main();
